# **********************************************************************************************************************
# Swagger property
# **********************************************************************************************************************
springdoc:
  api-docs:
    path:
      /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui-custom.html
